config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'


  devise_for :users
  root "home#index"
  get "/home/about" => "home#about"
  get "/home/delivery" => "home#delivery"
  get "/home/questions" => "home#questions"
  

  resources :products, only: [:index, :show] 
  resources :bulletins, only: [:index, :show]
  resources :abouts,only: [:index]
  resources :contacts 


  namespace :admin, path: "en1070416" do
    resources :products
    root "products#index"
    resources :bulletins
    resources :categories
    resources :contacts, only: [:index, :destroy]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  validates_presence_of :title

  belongs_to :category, optional: true
  mount_uploader :picture, ImageUploader

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :bulletins, dependent: :restrict_with_error
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name, :message
  validates :phone, format:{with: /\A09\d{8}\Z/}
  validates :email, format: { with: /\A[^@]+@[^@]+\z/}

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product
  mount_uploader :avatar, AvatarUploader

end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name
  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos, :allow_destroy => true
  #之後要做nested form，先設定接受變更photo底下的attribute
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  def admin?
    self.role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

    private
  def authenticate_admin
    if !current_user.admin?
      flash[:alert]="not allow"
      redirect_to root_path
    end
  end

end

app/controllers/admin/bulletins_controller.rb
class Admin::BulletinsController < Admin::BaseController
  before_action :set_bulletin, only: [:show, :edit, :update, :destroy]

  def index
    @bulletins = Bulletin.order(created_at: :desc).page(params[:page]).per(8)
  end

  def new
    @bulletin = Bulletin.new
  end

  def create
    @bulletin = Bulletin.new(bulletin_params)
    if @bulletin.save
      flash[:notice]= "Bulletin was successfully created"
      redirect_to admin_bulletins_path
    else
      flash[:alert]= " was failed to create"
      render :new
    end
  end

  def update
    if @bulletin.update(bulletin_params)
      flash[:notice]= "Bulletin was successfully update"
      redirect_to admin_bulletins_path
    else
      flash[:alert]="Bulletin was failed to update"
      render :edit
    end
  end


  def destroy
    @bulletin.destroy
    redirect_to admin_bulletins_path
  end


  private

    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end
    
    def bulletin_params
      params.require(:bulletin).permit(:title, :body, :author, :tag, :picture, :category_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authenticate_admin
    if !current_user.admin?
      flash[alert]="Page doesn't exist"
      redirect_to root_path
    end
  end
  
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).page(params[:page]).per(8)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
  end


  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Message was successfully created 訊息傳送成功"
      redirect_to contacts_path
      UserMailer.notify_contact_create(@contact).deliver_now!

    else
      flash.now[:alert] = "Message was failed created 請重新檢查欄位"
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).limit(1)
    @products = Product.all  
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end
  
  
  def about
  end

  def delivery
  end

  def questions
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show]

  def index
    @products = Product.all
  end

  def show
    @photos = @product.photos.all
    @products = Product.where.not(params[:id])
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/bulletins/_form.html.erb
<div class="container">
  <% if @bulletin.errors.any? %>
  <h3>We have some errors here!</h3>
  <ul>
  <% @bulletin.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  <% end %>

  <div class="pt-5 mt-5">
    <%= form_for [:admin, @bulletin] do |f| %>
    <div class="form-group">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div>
      <%= f.label :category, "Category"%>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "請選擇"}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :tag, 'Tag' %>
      <%= f.text_field :tag, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :author, 'Author' %>
      <%= f.text_field :author, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :picture, "Photo URL" %>
      <%= image_tag(@bulletin.picture) if @bulletin.picture? %>
      <%= f.text_field :remote_picture_url, class: "form-control" %>
    </div> 

    <div class="form-group">
      <%= f.label :body, "Body" %>
      <%= f.cktext_area :body, :class => 'someclass', :ckeditor => {:language => 'zh-tw'} %>
    </div>

    <div class="form-group">
      <%= f.label :picture, "Photo" %>
      <%= image_tag @bulletin.picture %>
      <%= f.file_field :picture, class: "form-control" %>
    </div>

    <div>
      <%= f.submit button, class: "btn btn-info" %>
    </div>

    <% end %>

  </div>
  
</div>

app/views/admin/bulletins/edit.html.erb
<%= render partial: 'form', locals: {button: "Update bulletin"} %>

app/views/admin/bulletins/index.html.erb
<div class="container">
  <h1>EnjoyRice後台</h1>

  <nav class="nav nav-pills nav-fill mt-5">
    <%= link_to "Product", admin_products_path, class: "nav-item btn-primary nav-link" %>
    <%= link_to "Bulletins", admin_bulletins_path, class: "nav-item btn-primary nav-link mx-5 active" %>
    <%#= link_to "Blog", admin_blogs_path, class: "nav-item nav-link"  %> 
    <%= link_to "Contact", admin_contacts_path, class: "nav-item btn-primary nav-link" %>
  </nav>
  <br>

  <div>
    <%= link_to "Add New Bulletin", new_admin_bulletin_path, class: "btn btn-info" %>
    <%= link_to "Categories", admin_categories_path, class: "btn btn-info" %>
  </div>
  <br>

  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Photo</th>
        <th scope="col">Title</th>
        <th scope="col">date</th>
        <th scope="col">tag</th>
        <th scope="col">body</th>
        <th scope="col">author</th>
        <th scope="col">category</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>

      </tr>
    </thead>
    <tbody>
      <% @bulletins.each do |bulletin| %>
      <tr>
        <th scope="row"><%=bulletin.id%></th>
        <td>
          <%= image_tag bulletin.picture.url(:small) unless bulletin.picture.blank? %>
          </td>
        <td><%= bulletin.title %></td>
        <td><%= bulletin.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= bulletin.tag %></td>
        <td><%= bulletin.body %></td>
        <td><%= bulletin.author %></td>
        <td><%= bulletin.category.name if bulletin.category %></td>
        <td><%= link_to 'Edit', edit_admin_bulletin_path(bulletin) %></td>
        <td><%= link_to 'Delete', admin_bulletin_path(bulletin), method: :delete, data: {confirm:"Are you sure?"} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class = "text-center">
    <%= paginate @bulletins %>
  </div>


</div>

app/views/admin/bulletins/new.html.erb
<%= render partial: "form", locals: {button: "Add"} %>

app/views/bulletins/_first.html.erb
<% @bulletins.each do |bulletin| %>
  <h5 class="d-inline"><%= bulletin.title %></h5>
  <p><%= bulletin.body.html_safe %></p>
<% end %>

app/views/bulletins/index.html.erb
  <div class="contact-bg top_bg">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-3-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-3-sm.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
    <div class="overlay"></div>
    <div class="toptitle-c">
      <div class="quotes-inner">
        <h3 class="mb-1">news</h3>
      </div>
    </div>
  </div>

    <div class="row contact-toptitle mt-4">
    <ol class="contact-title col-12 d-flex justify-content-center pr-md-3 pr-0">
      <li>最新消息</li>
 
    </ol>
  </div>

  <!-- bulltins -->
  <div class="container">
    
    <div class="bulletin pt-5"> 
        <div class="row">
          <% @bulletins.each do |bulletin| %> 
          <div class="col-12 col-sm-6 col-lg-4 mb-5">
            <div class="col-border p-2">
              <div class="bulletin-img">
                <% if bulletin.picture.present? %>
                  <%= image_tag(bulletin.picture.url, class: "img-fluid") %>
                <% else %>
                  <%= image_tag("http://placehold.it/300x200&text=No Pic", class: "img-fluid") %>
                <% end %>
              </div>
            <div class="bulletin-content my-3">
              <div class="er-font-18"><%= bulletin.title %></div>
                <div class="er-font-12 gray-color"><%= bulletin.created_at.strftime("%Y-%m-%d") %></div>
              <div class="er-font-16 mt-1"><%= bulletin.body.html_safe %></div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>


    <div>
      <div class=" er-pagination d-flex justify-content-center mt-4">
        <%= paginate @bulletins %>
      </div>
    </div>
     
  </div>