config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'


  devise_for :users
  root "home#index"
  get "/home/about" => "home#about"
  get "/home/delivery" => "home#delivery"
  get "/home/questions" => "home#questions"
  

  resources :products, only: [:index, :show] 
  resources :bulletins, only: [:index, :show]
  resources :abouts,only: [:index]
  resources :contacts 


  namespace :admin, path: "en1070416" do
    resources :products
    root "products#index"
    resources :bulletins
    resources :categories
    resources :contacts, only: [:index, :destroy]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  validates_presence_of :title

  belongs_to :category, optional: true
  mount_uploader :picture, ImageUploader

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :bulletins, dependent: :restrict_with_error
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name, :message
  validates :phone, format:{with: /\A09\d{8}\Z/}
  validates :email, format: { with: /\A[^@]+@[^@]+\z/}

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product
  mount_uploader :avatar, AvatarUploader

end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name
  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos, :allow_destroy => true
  #之後要做nested form，先設定接受變更photo底下的attribute
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  def admin?
    self.role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

    private
  def authenticate_admin
    if !current_user.admin?
      flash[:alert]="not allow"
      redirect_to root_path
    end
  end

end

app/controllers/admin/bulletins_controller.rb
class Admin::BulletinsController < Admin::BaseController
  before_action :set_bulletin, only: [:show, :edit, :update, :destroy]

  def index
    @bulletins = Bulletin.order(created_at: :desc).page(params[:page]).per(8)
  end

  def new
    @bulletin = Bulletin.new
  end

  def create
    @bulletin = Bulletin.new(bulletin_params)
    if @bulletin.save
      flash[:notice]= "Bulletin was successfully created"
      redirect_to admin_bulletins_path
    else
      flash[:alert]= " was failed to create"
      render :new
    end
  end

  def update
    if @bulletin.update(bulletin_params)
      flash[:notice]= "Bulletin was successfully update"
      redirect_to admin_bulletins_path
    else
      flash[:alert]="Bulletin was failed to update"
      render :edit
    end
  end


  def destroy
    @bulletin.destroy
    redirect_to admin_bulletins_path
  end


  private

    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end
    
    def bulletin_params
      params.require(:bulletin).permit(:title, :body, :author, :tag, :picture, :category_id)
    end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  
  def index
    @contacts = Contact.all.order(created_at: :desc)
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to admin_contacts_path
    flash[:alert]="Message was deleted"
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @photo = @product.photos.build

    #上傳圖
  end

  def show
    @photos = @product.photos.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save  
    if params[:photos] != nil
      params[:photos]['avatar'].each do |a|
        @photo = @product.photos.create(:avatar => a)                
          end
      end         
      flash[:notice]= "Product was successfully created"
      redirect_to admin_products_path
    else
    flash[:alert]= "Product was failed to create"
    render :new
    end
  end

  def update
    if params[:photos] != nil
      @product.photos.destroy_all  #首先要删除旧的图片
           
      params[:photos]['avatar'].each do |a|
        @photo = @product.photos.create!(:avatar => a)
      end
    end
    
    if @product.update(product_params)

      flash[:notice]= "Product was successfully update"
      redirect_to admin_products_path
    else
      flash[:alert]="Product was failed to update"
      render :edit
    end
  end


  def destroy
    @product.destroy
    redirect_to admin_products_path
  end


  private

    def set_product
      @product = Product.find(params[:id])
    end
    
    def product_params
      params.require(:product).permit(:name, :en_name, :description, :price, :flavor, :photo_id, photos_attributes: [:id, {avatar:[]}] )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authenticate_admin
    if !current_user.admin?
      flash[alert]="Page doesn't exist"
      redirect_to root_path
    end
  end
  
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).page(params[:page]).per(8)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
  end


  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Message was successfully created 訊息傳送成功"
      redirect_to contacts_path
      UserMailer.notify_contact_create(@contact).deliver_now!

    else
      flash.now[:alert] = "Message was failed created 請重新檢查欄位"
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).limit(1)
    @products = Product.all  
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end
  
  
  def about
  end

  def delivery
  end

  def questions
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show]

  def index
    @products = Product.all
  end

  def show
    @photos = @product.photos.all
    @products = Product.where.not(params[:id])
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/contacts/index.html.erb
<div class="container">
  <h1>EnjoyRice後台</h1>

  <nav class="nav nav-pills nav-fill mt-5">
    <%= link_to "Product", admin_products_path, class: "nav-item btn-primary nav-link" %>
    <%= link_to "Bulletins", admin_bulletins_path, class: "nav-item btn-primary nav-link mx-5" %>
    <%#= link_to "Blog", admin_blogs_path, class: "nav-item nav-link"  %> 
    <%= link_to "Contact", admin_contacts_path, class: "active nav-item btn-primary nav-link" %>
  </nav>
  <br>

  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Phone</th>
        <th scope="col">Email</th>
        <th scope="col">Message</th>
        <th scope="col">Delete</th>

      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
      <tr>
        <th scope="row"><%=contact.id%></th>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Delete', admin_contact_path(contact), method: :delete, data: {confirm:"Are you sure?"} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


</div>

app/views/admin/products/_form.html.erb
<div class="container">
  <% if @product.errors.any? %>
  <h3>We have some errors here!</h3>
  <ul>
  <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  <% end %>

  <div class="pt-5 mt-5">
    <%= form_for [:admin, @product] do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :en_name, "English Name" %>
      <%= f.text_field :en_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :flavor, 'Flavor' %>
      <%= f.text_field :flavor, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price, 'Price' %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :avatar, "Photo" %>
      <%= f.file_field :avatar, multiple: true, name: "photos[avatar][]" %>
    </div>

    <div>
      <%= f.submit button, class: "btn btn-info" %>
    </div>

    <% end %>
  </div>
  <br>
  
</div>

app/views/admin/products/edit.html.erb
<%= render partial: "form", locals: {button: "Update Product"} %>

app/views/admin/products/index.html.erb
<div class="container">
  <h1>EnjoyRice後台</h1>

  <nav class="nav nav-pills nav-fill mt-5">
      <%= link_to "Product", admin_products_path, class: "nav-item btn-primary nav-link active" %>
      <%= link_to "Bulletins", admin_bulletins_path, class: "nav-item btn-primary nav-link mx-5" %>
      <%#= link_to "Blog", admin_blogs_path, class: "nav-item nav-link"  %> 
      <%= link_to "Contact", admin_contacts_path, class: "nav-item btn-primary nav-link" %>
  </nav>
  <br>

  <div>
    <%= link_to "Add Product", new_admin_product_path, class: "btn btn-info" %>
  </div>
  <br>

  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Photo</th>
        <th scope="col">Name</th>
        <th scope="col">En_Name</th>
        <th scope="col">flavor</th>
        <th scope="col">price</th>
        <th scope="col">Description</th>
        <th scope="col">Edit</th>
        <th scope="col">Show</th>
        <th scope="col">Delete<th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>
        <th scope="row"><%=product.id%></th>
        <td>
          <% if product.photos.present? %>
            <%= image_tag(product.photos[0].avatar.small.url, class: "thumbnail") %>
          <% else %>
            <%= image_tag("http://placehold.it/80x80&text=No Pic", class: "thumbnail") %>
          <% end %>
        </td>

        <td><%= product.name %></td>
        <td><%= product.en_name %></td>
        <td><%= product.flavor %></td>
        <td>$<%= product.price %></td>
        <td><%= truncate(product.description, length:20) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Show', product_path(product) %></td>
        <td><%= link_to 'Delete', admin_product_path(product), method: :delete, data: {confirm:"Are you sure?"} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


</div>

app/views/admin/products/new.html.erb
<%= render partial: "form", locals: {button: "Add New Product"} %>

app/views/admin/products/show.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="col">
    <h2>Avatar</h2>
    <%# if @product.photos.present? %>
      <%#= image_tag(@product.photos[0].avatar.thumb.url, class: "thumbnail") %>
    <%# end %>

  </div>
  <div class="col">
  <li><%= @product.name %></li>
  <li><%= @product.en_name %></li>
  <li><%= @product.flavor %></li>
  <li>$<%= @product.price %></li>
  <li><%= @product.description %></li>
  </div>
  </div>
</div>

app/views/contacts/index.html.erb
  <div class="contact-bg top_bg">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-7-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-7-sm.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
    <div class="overlay"></div>
    <div class="toptitle-c">
      <div class="quotes-inner">
        <h3 class="mb-1">contact</h3>
      </div>
    </div>
  </div>

    <div class="row contact-toptitle mt-4">
    <ol class="contact-title col-12 d-flex justify-content-center pr-md-3 pr-0">
      <li class="front-title"><%= link_to '外送範圍', home_delivery_path, class:"gray-text" %></li>
      <li class="front-title"><%= link_to '訂購Q&A', home_questions_path, class: "gray-text" %> </li>
      <li>聯絡我們</li>
    </ol>
  </div>

  <h3 class="text-center my-4">contact</h3>

  <!-- form -->
<div class = "container col-md-8">
  
  <%= simple_form_for @contact do |f| %>
    <div class = "form-group">
      <%= f.input :name, placeholder: "姓名 Input your name", error: '請填寫姓名', class: "form-control" %>
    </div>

    <div class = "form-group">
      <%= f.input :phone, placeholder:"手機 Input your phone number", error: '您的手機號碼須為10個數字', required: true, class: "form-control" %>
    </div>

    <div class = "form-group">
    <%= f.input :email, placeholder:"電子信箱 Email", error:'您的email格式不正確', required: true, class: "form-control" %>
    </div>

    <div class = "form-group">
    <%= f.input :message, placeholder:"留下你的建議 Write the messages", error: '請留下您的訊息', class: "form-control form-pb" %>
    </div>

    <div class ="btngroup">
    <%= f.submit '送出', class:"btn-b" %>
    </div>

  <% end %>


</div>

app/views/products/index.html.erb
  <div class="menu-bg top_bg">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-1-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-1-sm.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
    <div class="overlay"></div>
    <div class="menu-toptitle">
      <div class="quotes-inner">
        <h5 class="border-w">手作原味餐盒</h5>
      </div>
    </div>
  </div>

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-5 col-md-3 top_bg">
        <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-9.jpg" alt="玩飯餐盒" class="img-fluid ">
        <div class="menu-imgtitle"><p>紅藜麥飯</p></div>
      </div>
      <div class="col-5 col-md-3 top_bg">
        <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-8.jpg" alt="玩飯餐盒" class="img-fluid ">
        <div class="menu-imgtitle"><p>手作配菜</p></div>
      </div>
      <div class="col-5 col-md-3 top_bg">
        <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-7.jpg" alt="玩飯餐盒" class="img-fluid ">
        <div class="menu-imgtitle"><p>慢熟主菜</p></div>
      </div>
      <div class="col-5 col-md-3 top_bg ">
        <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-6.jpg" alt="玩飯餐盒" class="img-fluid ">
        <div class="menu-imgtitle"><p>自製沾醬</p></div>
      </div>
    </div>

    <div class="index-title my-5">
      <hr><span class="index-span">會議餐盒</span>
    </div>

  <!-- menu column --> 
  <div class="menu-col">
    <div class="row d-flex justify-content-center">  
      <% @products.each do |product| %>  
            
        <div class="col-md-6 col-10">
          <div class="box px-0">
            <div class="menu-img">
              <% if product.photos.present? %>
                <%= image_tag(product.photos[0].avatar.url, class: "img-fluid") %>
              <% else %>
                <%= image_tag("http://placehold.it/300x200&text=No Pic", class: "img-fluid") %>
              <% end %>
            </div>
          </div>
        </div>   
      
          <div class="col-md-6 col-10 px-3 mt-3">
            <div class="menu-page-right">
              <div class="menu-page-top">
                <h5 class="d-inline mr-2"><%= product.name %></h5>
                <div class="er-font-14 d-inline px-1 pink-bg"><%= product.flavor %></div>
                <div class="er-font-14"><%= product.en_name %></div>
                <div class="er-font-14">$<%= product.price %></div>
              </div>
            </div>
              
            <hr>
              <div class="menu-content">
                <p><%= product.description %></p>
              </div>
          </div>
           <div class="w-100 mb-5"></div>
      <% end %>
    </div>
  </div>
   
  <div class="d-flex justify-content-center ">
    <a href="https://line.me/R/ti/p/%40kuo1137i" class= "col-5 text-center btn-mb-w mx-4 px-4 er-link" target="_blank">線上預訂</a>
  </div>

  </div>

  <!-- menu-quote -->
  <div class="menu-quote mb-5">
    <div class="quote-bg">
        <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-6-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
        <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-6-sm.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
      <div class="overlay"></div>
      <div class="quotes">
        <div class="quotes-inner">
          <h5 class="font-weight-light">Bon appetit</h5>
          <p class="font-weight-light">享受美食，不需要理由</p>
        </div>
      </div>
    </div>
  </div>