config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'


  devise_for :users
  root "home#index"
  get "/home/about" => "home#about"
  get "/home/delivery" => "home#delivery"
  get "/home/questions" => "home#questions"
  

  resources :products, only: [:index, :show] 
  resources :bulletins, only: [:index, :show]
  resources :abouts,only: [:index]
  resources :contacts 


  namespace :admin, path: "en1070416" do
    resources :products
    root "products#index"
    resources :bulletins
    resources :categories
    resources :contacts, only: [:index, :destroy]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  validates_presence_of :title

  belongs_to :category, optional: true
  mount_uploader :picture, ImageUploader

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :bulletins, dependent: :restrict_with_error
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name, :message
  validates :phone, format:{with: /\A09\d{8}\Z/}
  validates :email, format: { with: /\A[^@]+@[^@]+\z/}

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product
  mount_uploader :avatar, AvatarUploader

end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name
  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos, :allow_destroy => true
  #之後要做nested form，先設定接受變更photo底下的attribute
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  def admin?
    self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authenticate_admin
    if !current_user.admin?
      flash[alert]="Page doesn't exist"
      redirect_to root_path
    end
  end
  
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).page(params[:page]).per(8)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
  end


  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Message was successfully created 訊息傳送成功"
      redirect_to contacts_path
      UserMailer.notify_contact_create(@contact).deliver_now!

    else
      flash.now[:alert] = "Message was failed created 請重新檢查欄位"
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).limit(1)
    @products = Product.all  
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end
  
  
  def about
  end

  def delivery
  end

  def questions
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show]

  def index
    @products = Product.all
  end

  def show
    @photos = @product.photos.all
    @products = Product.where.not(params[:id])
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer container-fluid  bg-dark">
  <div class="container">
    <div class="footer-content pt-3">
      <div class="footer-icon">
        <div onclick="topFunction()" id="myBtn" title="Go to top"><i class="fas fa-arrow-circle-up fa-2x"></i></div>
        
      </div>

      <!-- mobile -->
      <div class="footer-info d-block d-md-none ">
        <div class="footer-col text-center">
          <p>LINE訂餐：@quo1137i</p> 
          <p>外送專線：0900-792620</p>
          <p>營業時間：週一～週五 09:30-17:00</p>
          <p>自取地址：新北市新莊區中正路366號(工作室不對外開放)</p>
        </div>
      </div>
      
      <!-- desktop -->
      <div class="d-none d-md-block mb-2">
        <div class="row footer-info d-inline-flex  bd-highlight px-4 mr-4">
          <div class="footer-col bd-highlight mr-4">
            <p>SERVICE</p>
            <p>LINE訂餐：@quo1137i</p> 
            <p>外送專線：0900-792620</p>
          </div>
          <div class="footer-col bd-highlight">
            <p>ABOUT</p>
            <p>營業時間：週一～週五 09:30-17:00</p>
            <p>自取地址：<a href="https://goo.gl/maps/C2j1obBZVfL2" target="_blank">新北市新莊區中正路366號1F</a>(工作室不對外開放)</p>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
    <div class="footer-social-icon text-center mb-2">
      <a href="https://www.facebook.com/enjoyrice/" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
      <a href="https://www.instagram.com/enjoyrice.tw/" target="_blank"><i class="fab fa-line fa-2x"></i></a>
      <a href="https://line.me/R/ti/p/%40kuo1137i" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
    </div>
  </div>
    
    <div class="copyright text-center ">
      <p><small>&copy;2018 EnjoyRice玩飯職人 版權所有 | website design by mspink</small></p>
    </div> 
</div>

app/views/layouts/_icon.html.erb
      <a href="/cart">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 511.808 511.808" style="enable-background:new 0 0 511.808 511.808;" xml:space="preserve" width="25px" height="50px" class="svg">
      <g>
      <g>
      <path d="M477.511,491.424l-26.48-348.832c-0.624-8.336-7.584-14.784-15.952-14.784H76.391c-8.368,0-15.328,6.448-15.952,14.8    l-26.704,352c-0.336,4.432,1.2,8.816,4.224,12.08c3.024,3.264,7.28,5.12,11.728,5.12h412.112c0.096,0,0.208,0,0.32,0    c8.832,0,16-7.168,16-16.016C478.119,494.288,477.911,492.816,477.511,491.424z M66.935,479.808l24.288-320h329.024l24.288,320    H66.935z" fill="#FFFFFF"/>
      </g>
      </g>
      <g>
      <g>
      <path d="M255.735,0c-70.576,0-128,57.44-128,128.032v63.776c0,8.832,7.168,16,16,16c8.832,0,16-7.168,16-16v-63.776    c0-52.96,43.056-96.032,96-96.032c52.944,0,96,43.072,96,96.032v63.776c0,8.832,7.168,16,16,16c8.832,0,16-7.168,16-16v-63.776    C383.735,57.44,326.311,0,255.735,0z" fill="#FFFFFF"/>
      </g>
      </g>
      </svg>
</a>

app/views/layouts/_navbar.html.erb
<div class="enav fixed-top navbar-dark bg-dark">
  <div class="container">
    <nav class="d-flex justify-content-md-start justify-content-between mx-2">
      <div class="order-2 order-md-1">
          <div class="navbar-brand">
            <%= link_to root_path do %>
              <div class="brand-logo d-block d-md-none">
                 <img src="<%= image_path('logo.png') %>" alt="App Logo"  >
              </div>
              <div class="brand-logo d-none d-md-block">
                 <img src="<%= image_path('logo.png') %>" alt="App Logo"  >
              </div>
            <% end %>
          </div>
      </div>
      <div class="order-1 order-md-2 d-md-none bar">
        <div class="bar navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i></div>
      </div>

      <div class="order-1 order-md-2 mr-md-auto d-none d-md-block">
        <ul class="navbar list-unstyled">
          <li class="nav-item">
            <%= link_to '關於我們', home_about_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯美味', products_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯快訊', bulletins_path,class: "nav-link" %>
          </li>

          <li>
          <div class="dropdown show">
            <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">服務資訊</a>

          <div class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuLink">
          <%= link_to '外送範圍', home_delivery_path, class: "dropdown-item" %>
          <%= link_to '聯絡我們', contacts_path, class: "dropdown-item" %>
          <%= link_to '訂購Q&A', home_questions_path, class: "dropdown-item" %>
          </div>
        </div>
          </li>

          <li>
            <% if current_user&.admin? %>
              <%= link_to 'Admin Panel', admin_root_path %>
              <%= link_to'登出', destroy_user_session_path, method: :delete %>

              <% end %>
          </li>
        </ul>
      </div>
        <div class="order-3 order-md-3 mr-md-auto d-md-none d-block">
          <p> </p>
        </div>
    </nav>     
  </div>
</div>

<!-- mobile -->

    <nav class="ernav collapse navbar-collapse bg-dark mt-5 " id="navbarSupportedContent">
        <ul class="navbar-nav ml-3 list-unstyled">
          <li class="nav-item">
            <%= link_to '關於我們', home_about_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯美味', products_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯快訊', bulletins_path,class: "nav-link" %>
          </li>

          <li>
          <div class="dropdown show">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">服務資訊</a>

            <div class="dropdown-menu bg-dark border-0" aria-labelledby="dropdownMenuLink">
              <%= link_to '外送範圍', home_delivery_path, class: "dropdown-item " %>
              <%= link_to '聯絡我們', contacts_path, class: "dropdown-item" %>
              <%= link_to '訂購QA', home_questions_path, class: "dropdown-item" %>
            </div>
          </div>
          </li>
          <!-- 會員資訊 -->
          <li>
   
            <% if current_user&.admin? %>
              <%= link_to 'Admin Panel', admin_root_path %>
            <% end %>

          </li>

        <div class="footer-social-icon mt-5 mb-3 p-2 d-block d-md-none">
          <a href="https://www.facebook.com/enjoyrice/" target="_blank"><i class="fab fa-facebook-f fa-lg"></i></a>
          <a href="https://www.instagram.com/enjoyrice.tw/" target="_blank"><i class="fab fa-line fa-lg"></i></a>
          <a href="https://line.me/R/ti/p/%40kuo1137i" target="_blank"><i class="fab fa-instagram fa-lg"></i></a>
        </div>

      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiceShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- header -->
    <header>
      <%= render partial: "layouts/navbar" %>
    </header>

    
    <!-- Notice bar -->   
    <% if flash[:notice] %>
      <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif flash[:alert] %>
      <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
   

    <%= yield %>
  </body>
    
  <footer>
    <%= render partial: "layouts/footer" %>
  </footer>

</html>